### PR TITLE
Fix unmatched param bug

### PR DESCRIPTION
**Pull request by bowiec**
Hi! I ran into a bug when using pydapper on my project when parameters are specified, but not used in the SQL query. In that case, it would throw a missing key exception. This might seem like a contrived situation, but it is an issue when using query_multiple where not all queries have parameters specified (which is what happened to me).

I also noticed the `codecov` package version in use is no longer available and was causing the install to fail so I updated it.

### CODE REVIEW

**Comment by zschumacher** [comment]
codecov actually deleted their python uploader from pypi, I'll put in a separate PR to fix that in CI

**Comment by bowiec** [comment]
Sure, here's a minimum example:
```python
param = {
    "val": 1,
}

sql = (
    "select 1",
    "select ?val?"
)

val1, val2 = commands.query_multiple(sql, models=(dict, dict), param=param)
```

This results in this exception:
```
KeyError: "Key '' can not be accessed on {'val': 1} or does not exist"
obj = {'val': 1}, key = ''

    def safe_getattr(obj: Any, key: str) -> Any:
        try:
            if isinstance(obj, dict):
>               return obj[key]
E               KeyError: ''
```

**Comment by zschumacher** [comment]
hey man - sorry I'm taking so long getting back to this, been a crazy few months for me. Lets try to get this merged this week.

**Review by zschumacher — APPROVED** [review]

**Comment by bowiec** [comment]
No worries, thanks for reviewing!

**Pull request merged**
