### PR TITLE
✨ add support for `psycopg3`

### PR DESCRIPTION
**Pull request by idumancic**
I have not set `psycopg3` as a default dbapi driver for PostgreSQL in `pydapper`. 

But we can change that if you decide to do so.

### CODE REVIEW

**Comment by zschumacher** [comment]
This looks great, thank you! Once comment - I don’t think we need both psycopg and psycopg-binary as deps. Can we keep just the binary?

**Comment by idumancic** [comment]
> This looks great, thank you! One comment - I don’t think we need both psycopg and psycopg-binary as deps. Can we keep just the binary?

From my understanding `psycopg-binary` is an optional package from this version, when I only include the binary the tests fail because there is no `psycopg` to import.

https://pypi.org/project/psycopg-binary/ -> You can read here the description

**Comment by zschumacher** [comment]
ah okay - can you remove it and reinstall it like 
```bash
poetry add 'psycopg[binary]' --optional
```
should add it to the toml how i would expect.  Didn't realize it was just an extra

**Comment by idumancic** [comment]
> ```shell
> poetry add 'psycopg[binary]' --optional
> ```

Should be good now.

**Comment by zschumacher** [comment]
Doesn't need to happen in this PR, but I would also like to add the psycopg3 async api as one of the async drivers.  If you wanted to PR that that'd be amazing, otherwise I'll look to add it in a couple weeks

**Review by zschumacher — APPROVED** [review]

**Comment by idumancic** [comment]
> Doesn't need to happen in this PR, but I would also like to add the psycopg3 async api as one of the async drivers. If you wanted to PR that that'd be amazing, otherwise I'll look to add it in a couple weeks

https://github.com/zschumacher/pydapper/pull/218 here it is :)

**Pull request merged**
